spring:
  application:
    name: $artifactId
    version: @project.version@
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}


